

'use strict';

var TILE_WIDTH = 32;
var GAME_FPS = 40;
var MOVE_STAND = 0;
var MOVE_LEFT = 1;
var MOVE_RIGHT = 2;
var MOVE_DOWN = 3;
var MOVE_UP = 4;
var MOVE_TURN = 5;
var MOVE_ICE_MAKE = 6;
var MOVE_ICE_REMOVE = 7;
var MOVE_ICE_MOVING = 8;
var MOVE_ICE_CHECK = 9;
var MOVE_PUSH = 8;

var DIR_LEFT = -1;
var DIR_RIGHT = 1;

var ANIM_STANDARD_DELAY = 2;
var ANIM_FRAME_COUNT = 16;
var ANIM_LEFT_ROW = 1;
var ANIM_RIGHT_ROW = 0;
var ANIM_RUN_START = 0;
var ANIM_RUN_END = 3;
var ANIM_STAND = 4;
var ANIM_TURN_START = 4;
var ANIM_TURN_END = 7;
var ANIM_FALL_START = 8;
var ANIM_FALL_END = 9;
var ANIM_BIG_FALL_START = 10;
var ANIM_BIG_FALL_END = 11;
var ANIM_PUSH_START = 12;
var ANIM_PUSH_END = 13;
var ANIM_JUMP_START = 14;
var ANIM_JUMP_END = 15;
var ANIM_STAND_START = 16;
var ANIM_STAND_END = 17;
var ANIM_ICE_START = 18;
var ANIM_ICE_END = 19;
var ANIM_CROUCH_START = 20;
var ANIM_CROUCH_END = 22;

var TILE_MIDDLE = 0;
var TILE_LEFT = 32;
var TILE_RIGHT = 64;
var TILE_BOTH = 96;
var TILE_TOP = 128;
var TILE_BOTTOM = 160;

var OBJECT_BACKGROUND = 0;
var OBJECT_NULL = 999;
var OBJECT_WALL = 1;
var OBJECT_FIRE = 666;
var OBJECT_ICE = 333;
var OBJECT_OUT = 255;
var OBJECT_PLAYER = 777;
